# Generated by Django 3.0.3 on 2020-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='게시물 ID')),
                ('title', models.CharField(max_length=100, verbose_name='게시물 제목')),
                ('description', models.TextField(verbose_name='게시물 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시물 작성 시간')),
            ],
        ),
    ]
