# Generated by Django 3.0.3 on 2020-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='게시물 제목')),
                ('description', models.TextField(verbose_name='게시물 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시물 작성 시간')),
            ],
        ),
    ]
